import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { css, keyframes } from '@emotion/css';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { GrafanaTheme2, renderMarkdown } from '@grafana/data';
import { locationService } from '@grafana/runtime';
import { Button, Icon, IconButton, TextArea, useStyles2 } from '@grafana/ui';
import { useAgentChat, ChatMessage } from './use-agent-chat';
import { extractPageContext, hasPageContext } from '../lib/page-context';
import { PageContext } from '../lib/protocol';
import { fetchSuggestions } from '../lib/chat-stream';
import { contextVariants, messageVariants } from '../lib/motion';
import { ThinkingBlock } from './ThinkingBlock';
import { JsonBlock } from './JsonBlock';
import { Branding, isSafeIconSrc, loadBranding } from '../lib/branding';
import {
  ChatSession,
  clearAutoAllow,
  deriveTitle,
  loadStore,
  newSession,
  saveStore,
} from '../lib/chat-store';
import { useCustomContext } from '../lib/use-custom-context';
import { turnDumpJson } from '../lib/debug-dump';

/**
 * ChatPanel is the reusable chat surface used inside the slide-in drawer. It:
 *  - reads the current Grafana page context and prefills a suggested question,
 *  - streams the agent's answer token-by-token,
 *  - persists every conversation to localStorage and lets the user browse and
 *    resume prior threads via an inline history list.
 *
 * All motion is framer-motion driven and respects reduced-motion preferences.
 */

type Props = {
  /** Compact layout tuned for the drawer width. */
  compact?: boolean;
  /** When provided, renders a close control in the header (drawer mode). */
  onClose?: () => void;
};

export function ChatPanel({ onClose }: Props) {
  const styles = useStyles2(getStyles);
  const reduceMotion = useReducedMotion();

  /* Session state is initialised once from localStorage. */
  const [sessions, setSessions] = useState<ChatSession[]>(() => loadStore().sessions);
  const [activeId, setActiveId] = useState<string>(() => {
    const store = loadStore();
    return store.activeId && store.sessions.some((s) => s.id === store.activeId)
      ? store.activeId
      : (store.sessions[0]?.id ?? '');
  });
  const [historyOpen, setHistoryOpen] = useState(false);
  const [contextOpen, setContextOpen] = useState(false);
  const [branding, setBranding] = useState<Branding>({});

  /* Operator branding (custom icon/name) is fetched once and cached; falls back
   * to the built-in glyph and labels when unset. */
  useEffect(() => {
    let cancelled = false;
    void loadBranding().then((b) => {
      if (!cancelled) {
        setBranding(b);
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const active = useMemo(
    () => sessions.find((s) => s.id === activeId) ?? null,
    [sessions, activeId],
  );

  const { messages, busy, interaction, respond, allowAlways, send, cancel, load } = useAgentChat(
    active?.id ?? 'ephemeral',
    active?.messages ?? [],
  );

  const [input, setInput] = useState('');
  const [pageContext, setPageContext] = useState<PageContext>({});
  /* Context-derived follow-up questions shown as tappable hint chips, never
   * pre-filled into the input — tapping one fills the composer. They are
   * generated by the backend model from the conversation so far, so they only
   * exist once the user has actually said something, and they are tagged with
   * the chat they were generated for: switching threads must never surface
   * another thread's follow-ups. */
  const [suggestions, setSuggestions] = useState<{ sessionId: string; items: string[] }>({
    sessionId: '',
    items: [],
  });
  const [suggesting, setSuggesting] = useState(false);
  /* Standing user preference that steers suggestions. Owned by a hook so it is
   * identical across chats, drawer open/close cycles, reloads, and tabs. */
  const { value: customContext, setValue: setCustomContext } = useCustomContext();
  const [customContextOpen, setCustomContextOpen] = useState<boolean>(
    () => customContext.trim().length > 0,
  );
  const suggestAbortRef = useRef<AbortController | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  /* Ask the backend for fresh follow-up suggestions from the latest state.
   * Only runs once the conversation has actual content — suggestions are
   * follow-ups, so an empty chat gets none (the empty state already explains
   * what to do). Results are tagged with the session they belong to and
   * in-flight requests are aborted so only the newest wins. */
  const refreshSuggestions = useCallback(
    (args: { sessionId: string; msgs: ChatMessage[]; ctx: PageContext }) => {
      suggestAbortRef.current?.abort();
      const controller = new AbortController();
      suggestAbortRef.current = controller;

      const history = args.msgs
        .filter((m) => m.content.trim().length > 0)
        .slice(-10)
        .map((m) => ({ role: m.role, content: m.content }));

      /* No conversation yet: nothing to follow up on. */
      if (history.length === 0) {
        setSuggesting(false);
        setSuggestions({ sessionId: args.sessionId, items: [] });
        return;
      }

      setSuggesting(true);
      void fetchSuggestions(
        { history, pageContext: args.ctx, customContext: customContext.trim() || undefined },
        controller.signal,
      ).then((next) => {
        if (!controller.signal.aborted) {
          setSuggestions({ sessionId: args.sessionId, items: next });
          setSuggesting(false);
        }
      });
    },
    [customContext],
  );

  /* Signature of the last context we published. Extraction walks the scene
   * graph and hits the dashboard API, and its result feeds an effect that asks
   * the backend for suggestions — so publishing an identical-but-new object
   * would cost a model call for nothing. Explore rewrites the URL on almost
   * every interaction, which makes that churn constant. */
  const contextSigRef = useRef<string>('');

  const publishContext = useCallback((ctx: PageContext) => {
    const signature = JSON.stringify(ctx);
    if (signature === contextSigRef.current) {
      return;
    }
    contextSigRef.current = signature;
    setPageContext(ctx);
  }, []);

  const refreshContext = useCallback(() => {
    void extractPageContext().then(publishContext);
  }, [publishContext]);

  /* Extract context on mount, retry briefly (Scenes dashboards hydrate async so
   * the first extraction after login/navigation often sees nothing), and
   * re-extract on every URL change so the panel tracks the page being viewed.
   * URL changes are debounced: Explore pushes a new URL for every query, pane,
   * and time-range tweak, and each extraction is comparatively expensive. */
  useEffect(() => {
    let cancelled = false;
    let debounce = 0;
    const attempt = (retriesLeft: number) => {
      void extractPageContext().then((ctx) => {
        if (cancelled) {
          return;
        }
        publishContext(ctx);
        if (!hasPageContext(ctx) && retriesLeft > 0) {
          window.setTimeout(() => attempt(retriesLeft - 1), 700);
        }
      });
    };
    attempt(3);

    const sub = locationService.getHistory().listen(() => {
      if (cancelled) {
        return;
      }
      window.clearTimeout(debounce);
      debounce = window.setTimeout(refreshContext, 400);
    });
    return () => {
      cancelled = true;
      window.clearTimeout(debounce);
      sub();
    };
  }, [publishContext, refreshContext]);

  /* If there is no session yet, create one lazily so history always has a home. */
  useEffect(() => {
    if (!active && sessions.length === 0) {
      const s = newSession();
      setSessions([s]);
      setActiveId(s.id);
    }
  }, [active, sessions.length]);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages]);

  /* Mirror the streamed conversation into the session list. Kept as a pure
   * updater — persistence is a separate, debounced effect below. */
  useEffect(() => {
    if (!activeId) {
      return;
    }
    setSessions((prev) =>
      prev.map((s) =>
        s.id === activeId
          ? { ...s, messages, title: deriveTitle(messages), updatedAt: Date.now() }
          : s,
      ),
    );
  }, [messages, activeId]);

  /* Persist to localStorage off the hot path: `messages` changes on every
   * streamed token, and each save serializes the whole history (tool outputs
   * included), which is enough synchronous work to visibly jank the page. */
  useEffect(() => {
    if (!activeId) {
      return;
    }
    const handle = window.setTimeout(() => {
      saveStore({ sessions, activeId });
    }, 400);
    return () => {
      window.clearTimeout(handle);
    };
  }, [sessions, activeId]);

  /* Regenerate follow-up suggestions when the turn is idle. Debounced so a
   * rapid burst of state changes (streaming settle + context re-extract)
   * collapses into one backend call. Runs after each answer and when the page
   * or custom context changes — never for an empty conversation. */
  useEffect(() => {
    if (busy || !activeId) {
      return;
    }
    const handle = window.setTimeout(() => {
      refreshSuggestions({ sessionId: activeId, msgs: messages, ctx: pageContext });
    }, 400);
    return () => {
      window.clearTimeout(handle);
    };
  }, [busy, messages, pageContext, activeId, refreshSuggestions]);

  const startNewChat = () => {
    const s = newSession();
    setSessions((prev) => [s, ...prev]);
    setActiveId(s.id);
    load([]);
    setHistoryOpen(false);
    setInput('');
    suggestAbortRef.current?.abort();
    setSuggesting(false);
    setSuggestions({ sessionId: s.id, items: [] });
    refreshContext();
  };

  const openSession = (id: string) => {
    const s = sessions.find((x) => x.id === id);
    if (!s) {
      return;
    }
    setActiveId(id);
    load(s.messages);
    setHistoryOpen(false);
    suggestAbortRef.current?.abort();
    setSuggesting(false);
    setSuggestions({ sessionId: id, items: [] });
  };

  const deleteSession = (id: string) => {
    clearAutoAllow({ sessionId: id });
    /* Computed outside the updater: state updaters must stay pure (React can
     * invoke them twice), and this one has to switch the active thread. */
    const next = sessions.filter((s) => s.id !== id);
    setSessions(next);
    if (id === activeId) {
      setActiveId(next[0]?.id ?? '');
      load(next[0]?.messages ?? []);
    }
  };

  const onSend = () => {
    const text = input.trim();
    if (!text) {
      return;
    }
    void send(text, pageContext);
    setInput('');
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      onSend();
    }
  };

  /* Guard against a late response from a previous thread painting chips here. */
  const visibleSuggestions = suggestions.sessionId === activeId ? suggestions.items : [];

  const initial = reduceMotion ? false : 'hidden';

  return (
    <div className={styles.root} data-testid="mcpagent-chat">
      <div className={styles.header}>
        <div className={styles.title}>
          <span className={styles.logo}>
            {isSafeIconSrc(branding.icon) ? (
              <img className={styles.logoImg} src={branding.icon} alt="" aria-hidden />
            ) : (
              <Icon name="comment-alt-share" size="lg" />
            )}
          </span>
          <div className={styles.titleText}>
            <span className={styles.titleMain}>{branding.name || 'MCP Agent'}</span>
            <span className={styles.titleSub}>{branding.subtitle || 'Context-aware assistant'}</span>
          </div>
        </div>
        <div className={styles.headerActions}>
          <IconButton
            name="history"
            aria-label="Chat history"
            tooltip="History"
            onClick={() => setHistoryOpen((v) => !v)}
            data-testid="mcpagent-history-toggle"
          />
          <IconButton
            name="plus"
            aria-label="New chat"
            tooltip="New chat"
            onClick={startNewChat}
            data-testid="mcpagent-new"
          />
          {onClose && (
            <IconButton
              name="times"
              aria-label="Close MCP Agent"
              tooltip="Close"
              onClick={onClose}
              data-testid="mcpagent-close"
            />
          )}
        </div>
      </div>

      <AnimatePresence initial={false}>
        {historyOpen && (
          <motion.div
            className={styles.history}
            variants={contextVariants}
            initial={initial}
            animate="visible"
            exit="exit"
            data-testid="mcpagent-history"
          >
            {sessions.length === 0 && <div className={styles.historyEmpty}>No conversations yet.</div>}
            {sessions.map((s) => (
              <div
                key={s.id}
                className={css(styles.historyItem, s.id === activeId && styles.historyItemActive)}
                onClick={() => openSession(s.id)}
                role="button"
                tabIndex={0}
              >
                <Icon name="comment-alt" size="sm" />
                <span className={styles.historyTitle}>{s.title}</span>
                <IconButton
                  name="trash-alt"
                  size="sm"
                  aria-label="Delete conversation"
                  tooltip="Delete"
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteSession(s.id);
                  }}
                />
              </div>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      <ContextDisclosure
        context={pageContext}
        open={contextOpen}
        onToggle={() => setContextOpen((v) => !v)}
        styles={styles}
        initial={initial}
      />

      <div className={styles.messages} ref={scrollRef} data-testid="mcpagent-messages">
        {messages.length === 0 && (
          <motion.div className={styles.empty} initial={initial} animate="visible" variants={messageVariants}>
            <div className={styles.emptyIcon}>
              <Icon name="ai" size="xxl" />
            </div>
            <div className={styles.emptyTitle}>Ask about what you&apos;re viewing</div>
            <div className={styles.emptyBody}>
              The agent reads your current dashboard, panel, and time range, and can call your configured MCP
              tools to investigate.
            </div>
          </motion.div>
        )}
        <AnimatePresence initial={false}>
          {messages.map((m) => (
            <MessageBubble
              key={m.id}
              message={m}
              pageContext={pageContext}
              styles={styles}
              initial={initial}
            />
          ))}
        </AnimatePresence>
      </div>

      <AnimatePresence initial={false}>
        {interaction && (
          <motion.div
            className={styles.interaction}
            variants={contextVariants}
            initial={initial}
            animate="visible"
            exit="exit"
            data-testid="mcpagent-interaction"
          >
            <div className={styles.interactionPrompt}>
              <Icon name={interaction.kind === 'confirm' ? 'shield' : 'question-circle'} size="sm" />
              <span className={styles.interactionText}>
                {interaction.kind === 'confirm' ? interaction.description : interaction.prompt}
              </span>
            </div>
            {interaction.kind === 'confirm' && (
              <div className={styles.interactionArgs}>
                <JsonBlock
                  label={interaction.toolName}
                  value={interaction.input}
                  tone="input"
                  defaultOpen
                />
              </div>
            )}
            <div className={styles.interactionActions}>
              {interaction.kind === 'confirm' ? (
                <>
                  <Button size="sm" onClick={() => respond('yes')} data-testid="mcpagent-confirm-allow">
                    Allow
                  </Button>
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={allowAlways}
                    data-testid="mcpagent-confirm-always"
                    tooltip="Skip approval prompts for the rest of this chat"
                  >
                    Always allow in this chat
                  </Button>
                  <Button
                    size="sm"
                    variant="destructive"
                    fill="outline"
                    onClick={() => respond('no')}
                    data-testid="mcpagent-confirm-deny"
                  >
                    Deny
                  </Button>
                </>
              ) : (
                <>
                  {(interaction.options ?? ['Done']).map((opt) => (
                    <Button
                      key={opt}
                      size="sm"
                      variant="secondary"
                      onClick={() => respond(opt)}
                      data-testid="mcpagent-answer"
                    >
                      {opt}
                    </Button>
                  ))}
                </>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className={styles.inputRow}>
        <AnimatePresence initial={false}>
          {visibleSuggestions.length > 0 && input.trim() === '' && !busy && !interaction && (
            <motion.div
              className={styles.suggestionRow}
              variants={contextVariants}
              initial={initial}
              animate="visible"
              exit="exit"
              data-testid="mcpagent-suggestions"
            >
              {visibleSuggestions.map((s) => (
                <button
                  key={s}
                  type="button"
                  className={styles.suggestion}
                  onClick={() => setInput(s)}
                  data-testid="mcpagent-suggestion"
                >
                  <Icon name="ai" size="sm" />
                  <span className={styles.suggestionText}>{s}</span>
                </button>
              ))}
            </motion.div>
          )}
        </AnimatePresence>

        <div className={styles.customContextBar}>
          <button
            type="button"
            className={styles.customContextToggle}
            onClick={() => setCustomContextOpen((v) => !v)}
            aria-expanded={customContextOpen}
            data-testid="mcpagent-customcontext-toggle"
          >
            <Icon name={customContextOpen ? 'angle-down' : 'angle-right'} size="sm" />
            <span>Steer suggestions{customContext.trim() ? ' •' : ''}</span>
          </button>
          {suggesting && <span className={styles.suggestingHint}>Thinking of suggestions…</span>}
        </div>
        <AnimatePresence initial={false}>
          {customContextOpen && (
            <motion.div
              className={styles.customContextWrap}
              variants={contextVariants}
              initial={initial}
              animate="visible"
              exit="exit"
            >
              <TextArea
                value={customContext}
                onChange={(e) => setCustomContext(e.currentTarget.value)}
                placeholder="Only shapes the suggested prompts below the chat, e.g. 'I own checkout; focus on latency and 5xx'. Not sent with your messages."
                rows={2}
                className={styles.textarea}
                data-testid="mcpagent-customcontext-input"
              />
            </motion.div>
          )}
        </AnimatePresence>

        <div className={styles.inputWrap}>
          <TextArea
            value={input}
            onChange={(e) => setInput(e.currentTarget.value)}
            onKeyDown={onKeyDown}
            placeholder="Ask anything about this page…"
            rows={2}
            className={styles.textarea}
            data-testid="mcpagent-input"
          />
          <AnimatePresence mode="wait" initial={false}>
            {busy ? (
              <motion.div
                key="stop"
                className={styles.sendBtn}
                initial={reduceMotion ? false : { opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
              >
                <Button
                  variant="destructive"
                  icon="square-shape"
                  onClick={cancel}
                  aria-label="Stop"
                  tooltip="Stop"
                  className={styles.roundBtn}
                  data-testid="mcpagent-stop"
                />
              </motion.div>
            ) : (
              <motion.div
                key="send"
                className={styles.sendBtn}
                initial={reduceMotion ? false : { opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                whileTap={reduceMotion ? undefined : { scale: 0.94 }}
              >
                <Button
                  icon="message"
                  onClick={onSend}
                  disabled={!input.trim()}
                  aria-label="Send"
                  tooltip="Send"
                  className={styles.roundBtn}
                  data-testid="mcpagent-send"
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}

function MessageBubble({
  message,
  pageContext,
  styles,
  initial,
}: {
  message: ChatMessage;
  pageContext: PageContext;
  styles: ReturnType<typeof getStyles>;
  initial: 'hidden' | false;
}) {
  const isUser = message.role === 'user';

  if (isUser) {
    return (
      <motion.div
        className={css(styles.bubbleWrap, styles.bubbleWrapUser)}
        variants={messageVariants}
        initial={initial}
        animate="visible"
        exit="exit"
      >
        <div className={css(styles.bubble, styles.bubbleUser)}>
          <div className={styles.content}>{message.content}</div>
        </div>
      </motion.div>
    );
  }

  const hasAnswer = message.content.trim().length > 0;
  /* No `layout` here: animating height while tokens stream causes the bubble to
   * "squish"/reflow on every chunk. The stream itself provides the typewriter
   * effect; we just append a blinking caret while it's live. */
  return (
    <motion.div
      className={css(styles.bubbleWrap, styles.bubbleWrapAssistant)}
      variants={messageVariants}
      initial={initial}
      animate="visible"
      exit="exit"
    >
      <div className={styles.assistant}>
        <ThinkingBlock
          reasoning={message.reasoning}
          toolCalls={message.toolCalls}
          streaming={message.streaming}
          hasAnswer={hasAnswer}
          dumpJson={() => turnDumpJson({ message, pageContext })}
        />
        {hasAnswer && (
          <div className={styles.answer}>
            <span
              className={styles.markdown}
              dangerouslySetInnerHTML={{ __html: renderMarkdown(message.content) }}
            />
            {message.streaming && <span className={styles.caret} />}
          </div>
        )}
      </div>
    </motion.div>
  );
}

/**
 * Renders a compact, expandable summary of exactly what page context the agent
 * received. This makes the agent's awareness legible: when it says "I can't see
 * the dashboard", the user can open this to confirm whether context was
 * captured, and what.
 */
function ContextDisclosure({
  context,
  open,
  onToggle,
  styles,
  initial,
}: {
  context: PageContext;
  open: boolean;
  onToggle: () => void;
  styles: ReturnType<typeof getStyles>;
  initial: 'hidden' | false;
}) {
  const rows: Array<{ label: string; value: string }> = [];
  if (context.dashboardTitle) {
    rows.push({ label: 'Dashboard', value: context.dashboardTitle });
  }
  if (context.datasource) {
    rows.push({ label: 'Datasource', value: context.datasource });
  }
  if (context.timeRange) {
    rows.push({ label: 'Time range', value: `${context.timeRange.from} → ${context.timeRange.to}` });
  }
  const queries = context.queries ?? [];
  const hasContext = rows.length > 0 || queries.length > 0;

  const headline = hasContext
    ? `Agent sees ${queries.length > 0 ? `${queries.length} quer${queries.length === 1 ? 'y' : 'ies'}` : 'this page'}`
    : 'Agent has no page context';

  return (
    <div className={styles.context} data-testid="mcpagent-context">
      <button
        type="button"
        className={styles.contextHeader}
        onClick={onToggle}
        aria-expanded={open}
        data-testid="mcpagent-context-toggle"
      >
        <Icon name={hasContext ? 'eye' : 'eye-slash'} size="sm" />
        <span className={styles.contextHeadline}>{headline}</span>
        <Icon name={open ? 'angle-up' : 'angle-down'} size="sm" />
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            className={styles.contextBody}
            variants={contextVariants}
            initial={initial}
            animate="visible"
            exit="exit"
          >
            {!hasContext && (
              <div className={styles.contextEmpty}>
                No dashboard, panel, or query detected on this page. Open a dashboard or Explore, then
                reopen this chat to give the agent context.
              </div>
            )}
            {rows.map((r) => (
              <div key={r.label} className={styles.contextRow}>
                <span className={styles.contextLabel}>{r.label}</span>
                <span className={styles.contextValue}>{r.value}</span>
              </div>
            ))}
            {queries.length > 0 && (
              <div className={styles.contextQueries}>
                <span className={styles.contextLabel}>Queries</span>
                {queries.map((q, i) => (
                  <code key={i} className={styles.contextQuery}>
                    {q}
                  </code>
                ))}
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

const caretBlink = keyframes({
  '0%, 50%': { opacity: 1 },
  '50.01%, 100%': { opacity: 0 },
});

const getStyles = (theme: GrafanaTheme2) => ({
  root: css({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    background: theme.colors.background.primary,
  }),
  header: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing(1.5, 2),
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
  }),
  title: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    minWidth: 0,
  }),
  logo: css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    borderRadius: theme.shape.radius.default,
    color: theme.colors.primary.contrastText,
    background: `linear-gradient(135deg, ${theme.colors.primary.main}, ${theme.colors.primary.shade})`,
    boxShadow: theme.shadows.z1,
  }),
  logoImg: css({
    width: 22,
    height: 22,
    objectFit: 'contain',
    display: 'block',
    borderRadius: theme.shape.radius.default,
  }),
  titleText: css({ display: 'flex', flexDirection: 'column', lineHeight: 1.15, minWidth: 0 }),
  titleMain: css({ fontWeight: theme.typography.fontWeightBold, fontSize: theme.typography.body.fontSize }),
  titleSub: css({ fontSize: theme.typography.bodySmall.fontSize, color: theme.colors.text.secondary }),
  headerActions: css({ display: 'flex', alignItems: 'center', gap: theme.spacing(0.5) }),
  history: css({
    overflow: 'hidden',
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
    maxHeight: 260,
    overflowY: 'auto',
  }),
  historyEmpty: css({
    padding: theme.spacing(2),
    color: theme.colors.text.secondary,
    fontSize: theme.typography.bodySmall.fontSize,
    textAlign: 'center',
  }),
  historyItem: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    padding: theme.spacing(1, 2),
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    transition: 'background 120ms ease, color 120ms ease',
    '&:hover': {
      background: theme.colors.action.hover,
      color: theme.colors.text.primary,
    },
  }),
  historyItemActive: css({
    color: theme.colors.text.primary,
    background: theme.colors.action.selected,
  }),
  historyTitle: css({
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  context: css({
    background: theme.colors.background.secondary,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    overflow: 'hidden',
  }),
  contextHeader: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    width: '100%',
    padding: theme.spacing(1, 2),
    border: 'none',
    background: 'transparent',
    color: theme.colors.text.secondary,
    cursor: 'pointer',
    fontSize: theme.typography.bodySmall.fontSize,
    textAlign: 'left',
    '&:hover': { color: theme.colors.text.primary },
  }),
  contextHeadline: css({
    flex: 1,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  contextBody: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.75),
    padding: theme.spacing(0, 2, 1.5, 2),
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  contextEmpty: css({
    color: theme.colors.text.secondary,
    lineHeight: 1.4,
  }),
  contextRow: css({
    display: 'flex',
    gap: theme.spacing(1),
  }),
  contextLabel: css({
    color: theme.colors.text.secondary,
    minWidth: 84,
    flexShrink: 0,
  }),
  contextValue: css({
    color: theme.colors.text.primary,
    wordBreak: 'break-word',
  }),
  contextQueries: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.5),
  }),
  contextQuery: css({
    display: 'block',
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: theme.typography.size.xs,
    color: theme.colors.text.primary,
    background: theme.colors.background.primary,
    border: `1px solid ${theme.colors.border.weak}`,
    borderRadius: theme.shape.radius.default,
    padding: theme.spacing(0.5, 1),
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  }),
  messages: css({
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    padding: theme.spacing(2),
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
  }),
  empty: css({
    color: theme.colors.text.secondary,
    textAlign: 'center',
    margin: 'auto',
    maxWidth: '34ch',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: theme.spacing(1),
  }),
  emptyIcon: css({
    color: theme.colors.primary.text,
    opacity: 0.7,
  }),
  emptyTitle: css({
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.primary,
    fontSize: theme.typography.h5.fontSize,
  }),
  emptyBody: css({ fontSize: theme.typography.bodySmall.fontSize, lineHeight: 1.5 }),
  bubbleWrap: css({ display: 'flex' }),
  bubbleWrapUser: css({ justifyContent: 'flex-end' }),
  bubbleWrapAssistant: css({ justifyContent: 'flex-start' }),
  bubble: css({
    maxWidth: '85%',
    padding: theme.spacing(1, 1.5),
    borderRadius: theme.shape.radius.default,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    boxShadow: theme.shadows.z1,
  }),
  bubbleUser: css({
    background: `linear-gradient(135deg, ${theme.colors.primary.main}, ${theme.colors.primary.shade})`,
    color: theme.colors.primary.contrastText,
    borderBottomRightRadius: theme.spacing(0.5),
  }),
  content: css({ lineHeight: theme.typography.body.lineHeight }),
  assistant: css({ width: '100%', maxWidth: '100%' }),
  answer: css({
    lineHeight: theme.typography.body.lineHeight,
    wordBreak: 'break-word',
    color: theme.colors.text.primary,
  }),
  markdown: css({
    '& > *:first-child': { marginTop: 0 },
    '& > *:last-child': { marginBottom: 0 },
    '& p': { margin: theme.spacing(0, 0, 1) },
    '& ul, & ol': { margin: theme.spacing(0, 0, 1), paddingLeft: theme.spacing(2.5) },
    '& li': { margin: theme.spacing(0.25, 0) },
    '& h1, & h2, & h3, & h4': {
      margin: theme.spacing(1.5, 0, 0.5),
      fontWeight: theme.typography.fontWeightMedium,
      lineHeight: 1.3,
    },
    '& h1': { fontSize: theme.typography.h4.fontSize },
    '& h2': { fontSize: theme.typography.h5.fontSize },
    '& h3, & h4': { fontSize: theme.typography.body.fontSize },
    '& a': { color: theme.colors.text.link, textDecoration: 'underline' },
    '& strong': { fontWeight: theme.typography.fontWeightBold },
    '& code': {
      fontFamily: theme.typography.fontFamilyMonospace,
      fontSize: '0.9em',
      padding: theme.spacing(0.125, 0.5),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.secondary,
      /* Grafana's global styles set `code { white-space: nowrap }`, which makes
       * long inline snippets (e.g. TraceQL queries) overflow the panel. */
      whiteSpace: 'pre-wrap',
      overflowWrap: 'anywhere',
    },
    '& pre': {
      margin: theme.spacing(0, 0, 1),
      padding: theme.spacing(1),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.border.weak}`,
      overflowX: 'auto',
    },
    '& pre code': { padding: 0, background: 'transparent', whiteSpace: 'pre' },
    '& blockquote': {
      margin: theme.spacing(0, 0, 1),
      paddingLeft: theme.spacing(1.5),
      borderLeft: `3px solid ${theme.colors.border.medium}`,
      color: theme.colors.text.secondary,
    },
    '& table': { borderCollapse: 'collapse', margin: theme.spacing(0, 0, 1) },
    '& th, & td': {
      border: `1px solid ${theme.colors.border.weak}`,
      padding: theme.spacing(0.5, 1),
    },
  }),
  caret: css({
    display: 'inline-block',
    width: '2px',
    height: '1.05em',
    marginLeft: '2px',
    verticalAlign: 'text-bottom',
    background: theme.colors.primary.text,
    animation: `${caretBlink} 1s steps(1) infinite`,
  }),
  interaction: css({
    margin: theme.spacing(0, 2, 1, 2),
    padding: theme.spacing(1.5),
    borderRadius: theme.spacing(1.5),
    border: `1px solid ${theme.colors.warning.border}`,
    background: theme.colors.warning.transparent,
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1),
    minWidth: 0,
  }),
  interactionPrompt: css({
    display: 'flex',
    gap: theme.spacing(1),
    alignItems: 'flex-start',
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.primary,
    '& svg': { flexShrink: 0, marginTop: 2 },
  }),
  interactionText: css({
    minWidth: 0,
    overflowWrap: 'anywhere',
  }),
  /* The argument payload can be long (a full TraceQL query object), so it gets
   * its own scroll container rather than stretching the approval card. */
  interactionArgs: css({
    minWidth: 0,
  }),
  interactionActions: css({
    display: 'flex',
    gap: theme.spacing(1),
    flexWrap: 'wrap',
  }),
  suggestionRow: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1),
  }),
  suggestion: css({
    display: 'flex',
    alignItems: 'flex-start',
    gap: theme.spacing(1),
    width: '100%',
    padding: theme.spacing(1, 1.5),
    borderRadius: theme.spacing(1.5),
    border: `1px dashed ${theme.colors.border.medium}`,
    background: 'transparent',
    color: theme.colors.text.secondary,
    fontSize: theme.typography.bodySmall.fontSize,
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease, color 0.15s ease, background 0.15s ease',
    '&:hover': {
      borderColor: theme.colors.primary.border,
      color: theme.colors.text.primary,
      background: theme.colors.action.hover,
    },
    '& svg': { flexShrink: 0, marginTop: 2 },
  }),
  suggestionText: css({
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  }),
  customContextBar: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1),
  }),
  customContextToggle: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    padding: 0,
    border: 'none',
    background: 'transparent',
    color: theme.colors.text.secondary,
    fontSize: theme.typography.bodySmall.fontSize,
    cursor: 'pointer',
    '&:hover': { color: theme.colors.text.primary },
  }),
  suggestingHint: css({
    color: theme.colors.text.disabled,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  customContextWrap: css({
    marginBottom: theme.spacing(1),
  }),
  inputRow: css({
    padding: theme.spacing(2),
    borderTop: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
  }),
  inputWrap: css({
    display: 'flex',
    gap: theme.spacing(1),
    alignItems: 'flex-end',
    padding: theme.spacing(1),
    borderRadius: theme.spacing(1.5),
    background: theme.colors.background.primary,
    border: `1px solid ${theme.colors.border.medium}`,
    transition: 'border-color 120ms ease, box-shadow 120ms ease',
    '&:focus-within': {
      borderColor: theme.colors.primary.border,
      boxShadow: `0 0 0 1px ${theme.colors.primary.border}`,
    },
  }),
  textarea: css({
    flex: 1,
    minWidth: 0,
    border: 'none',
    background: 'transparent',
    boxShadow: 'none',
    resize: 'none',
    padding: theme.spacing(0.5, 0),
    minHeight: 36,
    '&:focus': { boxShadow: 'none' },
  }),
  sendBtn: css({
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  }),
  roundBtn: css({
    width: 36,
    height: 36,
    padding: 0,
    borderRadius: theme.spacing(1),
    justifyContent: 'center',
    '& svg': { margin: 0 },
  }),
});
